name: mulsim_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  adhan: ^1.1.14
  flutter_qiblah: ^1.0.3+2
  flutter_svg:
  geolocator:
  flutter_local_notifications: ^3.0.3
  location: ^3.2.4
  intl: 
  hijri: ^2.0.3
  geocoder: ^0.2.1
  timezone: ^0.5.6
  flutter_native_timezone: ^1.0.4
  cached_network_image: ^2.0.0
  threading:
  http:
  rxdart:
  device_info:
  flutter_native_splash: ^0.2.9
  flutter_launcher_icons: ^0.8.1
  google_maps_flutter:
  shared_preferences:
  google_fonts:
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_messaging: 
  android_alarm_manager:
  font_awesome_flutter:
  url_launcher:
  launch_review:
  nb_utils:
  cron:
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/prayers/
    - assets/lang/
flutter_native_splash:
  color: "#42a5f5"
  image: assets/icon/icon.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"